[package]
name = "hotswap"
version = "0.2.0"
authors = ["Ian Ornelas <ian.orn@gmail.com>"]
description = "Easy code swapping in running executables"
repository = "https://github.com/draivin/rust-hotswap"
license = "MIT"

[lib]
name = "hotswap"
plugin = true
